include:
  - ../backend/docker-compose.yml

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - backend
    volumes:
      - frontend-dist:/app/dist
    command: sh -c "npm install && npm run build" 
    working_dir: /app

volumes:
  frontend-dist:
